#!/usr/bin/env bash
# Starts, tests and stops the virtual classroom lab.
#   scripts/lab.sh up      generate secrets (once), build and start
#   scripts/lab.sh smoke   end-to-end test: login, block, check student PCs, automatic release
#   scripts/lab.sh down    stop and remove containers and volumes
set -euo pipefail

cd "$(dirname "$0")/../lab"
COMPOSE=(docker compose)
BASE_URL="http://127.0.0.1:8080"

zufall() { openssl rand -hex "$1"; }

neue_uuid() {
    if command -v uuidgen >/dev/null; then uuidgen | tr 'A-Z' 'a-z'; else cat /proc/sys/kernel/random/uuid; fi
}

erzeuge_env() {
    [[ -f .env ]] && return
    cat > .env <<EOF
# Generated by scripts/lab.sh for the local lab only. Not committed.
OPNSENSE_API_KEY=$(zufall 20)
OPNSENSE_API_SECRET=$(zufall 32)
REGEL_UUID=$(neue_uuid)
DB_PASSWORT=$(zufall 16)
DB_ROOT_PASSWORT=$(zufall 16)
LEHRER_PASSWORT=$(zufall 6)
ADMIN_PASSWORT=$(zufall 8)
EOF
    chmod 600 .env
    echo ".env mit Zufallswerten angelegt"
}

wert() { grep -E "^$1=" .env | cut -d= -f2-; }

# Retries a check until it succeeds or the time limit (seconds) is reached; prints real elapsed time.
warte_auf() {
    local beschreibung=$1 limit=$2; shift 2
    local start=$SECONDS
    while ((SECONDS - start < limit)); do
        if "$@" >/dev/null 2>&1; then echo "  ok: $beschreibung (nach $((SECONDS - start)) s)"; return 0; fi
        sleep 1
    done
    echo "  FEHLER: $beschreibung nach ${limit} s nicht erreicht" >&2
    return 1
}

client_online() { "${COMPOSE[@]}" exec -T "$1" nc -z -w 2 1.1.1.1 443; }
client_offline() { ! client_online "$1"; }

api() {
    curl -sf -b "$KEKSE" -H "X-Internetsteuerung: 1" -H "Content-Type: application/json" "$@"
}

anmelden() {
    KEKSE=$(mktemp)
    local seite token
    seite=$(curl -sf -c "$KEKSE" "$BASE_URL/anmelden")
    token=$(grep -o '<input[^>]*__RequestVerificationToken[^>]*>' <<<"$seite" | sed -E 's/.*value="([^"]*)".*/\1/' || true)
    [[ -n "$token" ]] || { echo "  FEHLER: kein Antiforgery-Token" >&2; return 1; }
    local ziel
    ziel=$(curl -s -o /dev/null -w '%{redirect_url}' -b "$KEKSE" -c "$KEKSE" \
        --data-urlencode "__RequestVerificationToken=$token" \
        --data-urlencode "benutzername=lehrer" \
        --data-urlencode "passwort=$(wert LEHRER_PASSWORT)" \
        "$BASE_URL/konto/anmelden")
    [[ "$ziel" == "$BASE_URL/" ]] || { echo "  FEHLER: Anmeldung umgeleitet nach '$ziel'" >&2; return 1; }
    echo "  ok: Anmeldung als lehrer"
}

case "${1:-}" in
    up)
        erzeuge_env
        "${COMPOSE[@]}" up -d --build
        warte_auf "Web-App /health" 120 curl -sf "$BASE_URL/health"
        echo
        echo "Lab läuft: $BASE_URL"
        echo "Anmeldung: lehrer / $(wert LEHRER_PASSWORT)   admin / $(wert ADMIN_PASSWORT)"
        ;;
    smoke)
        [[ -f .env ]] || { echo "Erst 'scripts/lab.sh up' ausführen" >&2; exit 1; }
        echo "1. Grundzustand"
        warte_auf "Web-App /health" 60 curl -sf "$BASE_URL/health"
        warte_auf "schueler-pc-1 online" 30 client_online schueler-pc-1
        anmelden
        api -X POST "$BASE_URL/api/raum/freigeben" >/dev/null || true

        echo "2. Sperre für 1 Minute über die REST-API der Web-App"
        api -X POST "$BASE_URL/api/raum/sperren" -d '{"dauerMinuten":1}' >/dev/null
        warte_auf "schueler-pc-1 offline" 15 client_offline schueler-pc-1
        warte_auf "schueler-pc-2 offline" 15 client_offline schueler-pc-2
        api "$BASE_URL/api/raum/status" | grep -q '"gesperrt":true'
        echo "  ok: Status meldet gesperrt"

        echo "3. Automatische Freigabe durch den Hintergrunddienst"
        warte_auf "schueler-pc-1 wieder online" 90 client_online schueler-pc-1
        api "$BASE_URL/api/raum/status" | grep -q '"gesperrt":false'
        echo "  ok: Status meldet frei"

        echo "4. Sperre ohne Zeitsteuerung und manuelle Freigabe"
        api -X POST "$BASE_URL/api/raum/sperren" -d '{"dauerMinuten":0}' >/dev/null
        warte_auf "schueler-pc-2 offline" 15 client_offline schueler-pc-2
        api -X POST "$BASE_URL/api/raum/freigeben" >/dev/null
        warte_auf "schueler-pc-2 wieder online" 15 client_online schueler-pc-2

        echo "5. Firewall lehnt falsche Zugangsdaten ab"
        code=$("${COMPOSE[@]}" exec -T firewall curl -sk -o /dev/null -w '%{http_code}' -u falsch:falsch https://localhost/api/firewall/filter/search_rule)
        [[ "$code" == "401" ]] && echo "  ok: HTTP 401" || { echo "  FEHLER: HTTP $code" >&2; exit 1; }

        echo
        echo "Smoke-Test bestanden"
        ;;
    down)
        "${COMPOSE[@]}" down -v
        ;;
    *)
        echo "Aufruf: scripts/lab.sh up|smoke|down" >&2
        exit 2
        ;;
esac
